import Head from 'next/head'
import { Header } from '@/components/home/Header'
import { About } from '@/components/home/About'
import { Reserve } from '@/components/home/Reserve'
import { Menus } from '@/components/home/Menus'
import { CocktailMenu } from '@/components/home/CocktailMenu'
import { Chef } from '@/components/home/Chef'
import { Customers } from '@/components/home/Customers'
import { Video } from '@/components/home/Video'
import { Laurels } from '@/components/home/Laurels'
import { Blog } from '@/components/home/Blog'
import { Main } from '@/components/home/Main'
import { Gallery } from '@/components/home/Gallery'
import { Contact } from '@/components/home/Contact'
import { Footer } from '@/components/home/Footer'
import { Home } from '@/components/home/Home'


export default function AppContainer() {
  return (
    <>
      <Head>
        <title>Gericht</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />
      <Main>
        <Home classProp="section__home" />
        <About classProp="section__about" />
        <Reserve classProp="section__reserve" />
        <Menus classProp="section__menus" />
        <CocktailMenu classProp="section__cocktail-menu"/>
        <Chef classProp="section__chef"/>
        <Customers classProp="section__customers"/>
        <Video classProp="section__video" />
        <Laurels classProp="section__laurels" />
        <Blog classProp="section__blog" />
        <Gallery classProp="section__gallery" />
        <Contact classProp="section__contact" />
      </Main>
      <Footer />
    </>
  )
}
